console.log(first.className = "yellow text-dark red")
console.log(first.classList)
first.classList.remove('red')
first.classList.add('red')
first.classList.append('red')
first.classList.toggle('red')
console.log(first.classList.contains('red'))
console.log(first.classList.toggle('red'))
